Update launcher

diff --git a/mac/launcher b/mac/launcher
--- a/mac/launcher
+++ b/mac/launcher
@@ -8,8 +8,8 @@ APP_JAR="eaf.jar"
 APP_NAME="Eaf"
 VM_ARGS=""
 
-# Set the working directory
-DIR=$(cd "$(dirname "$0")"; pwd)
+# Set the working directory to APP/contents/MacOS
+DIR=$(cd "$(dirname "$0")/../APP/contents/MacOS"; pwd)
 
 # Error message for NO JAVA dialog
 ERROR_TITLE="Cannot launch $APP_NAME"
@@ -23,11 +23,11 @@ elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]]; then
     _java="$JAVA_HOME/bin/java"
 else
     osascript \
-	-e "set question to display dialog \"$ERROR_MSG\" with title \"$ERROR_TITLE\" buttons {\"Cancel\", \"Download\"} default button 2" \
-	-e "if button returned of question is equal to \"Download\" then open location \"$DOWNLOAD_URL\""
-	echo "$ERROR_TITLE"
-	echo "$ERROR_MSG"
-	exit 1
+    -e "set question to display dialog \"$ERROR_MSG\" with title \"$ERROR_TITLE\" buttons {\"Cancel\", \"Download\"} default button 2" \
+    -e "if button returned of question is equal to \"Download\" then open location \"$DOWNLOAD_URL\""
+    echo "$ERROR_TITLE"
+    echo "$ERROR_MSG"
+    exit 1
 fi
 
 # Java version check
@@ -35,20 +35,13 @@ if [[ "$_java" ]]; then
     version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
     if [[ "$version" < "$JAVA_MAJOR.$JAVA_MINOR" ]]; then
         osascript \
-    	-e "set question to display dialog \"$ERROR_MSG\" with title \"$ERROR_TITLE\" buttons {\"Cancel\", \"Download\"} default button 2" \
-    	-e "if button returned of question is equal to \"Download\" then open location \"$DOWNLOAD_URL\""
-    	echo "$ERROR_TITLE"
-    	echo "$ERROR_MSG"
-    	exit 1
+        -e "set question to display dialog \"$ERROR_MSG\" with title \"$ERROR_TITLE\" buttons {\"Cancel\", \"Download\"} default button 2" \
+        -e "if button returned of question is equal to \"Download\" then open location \"$DOWNLOAD_URL\""
+        echo "$ERROR_TITLE"
+        echo "$ERROR_MSG"
+        exit 1
     fi
 fi
 
-# Run the application with console output enabled
-exec $_java $VM_ARGS \
-    -Dapple.laf.useScreenMenuBar=true \
-    -Dcom.apple.macos.use-file-dialog-packages=true \
-    -Djava.util.logging.ConsoleHandler.level=ALL \
-    -Xdock:name="$APP_NAME" \
-    -Xdock:icon="$DIR/../Resources/application.icns" \
-    -cp ".;$DIR;" \
-    -jar "$DIR/$APP_JAR"
+# Run the application
+exec $_java $VM_ARGS -Dapple.laf.useScreenMenuBar=true -Dcom.apple.macos.use-file-dialog-packages=true -Xdock:name="$APP_NAME" -Xdock:icon="$DIR/../../Resources/application.icns" -cp ".;$DIR;" -jar "$DIR/$APP_JAR"
